language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: 6uhrmittag
  password:
    secure: "Klct19OuiAd7opw0X4zZyT1JVN8NN3UDS3nwQ5S2+CRcgQFXe90msAdJiuaULCcHZD3RLR90C9XnsQeaitVLugxSiBOu1k9ENWewd8k4sG4kGg1JJNxG0ye4mpfUhLk4ubPJelmlU+fPLnZ0ikRR5WhL3I+Zpf5Us64PfFazUoouwnAtIKsOpxOSjRNKjAaYnT55zwwvgA1KkIeOgCWv0IdMAEe5Y5bqri2nK1ptJjSPWoVZgzWaeG9Jj7qZ3/WKji1g3oR1LK8wRJGveaxbrIU1Xbbsb/KczYHDAv+vtlJaqaUScP8Ad/OteHNfUqvLKKxGPUPIcXJC72LaZLKwWhSefrxvDeGH1EQTrJ/EwxOlTYURSvLQCtD725lb4pAtD63h2w3QtmBazcOwR/tyh6ZC5UI+XozXbxY8MsycQdOwLgy2iKAQ0nfzYnFw9DZ1WgW+iTkYYNAMCSnDl9oQLCxZWmrYoSBhofHD5ONlcsrRNti4r9luCGwN3pY+HFbw8+eQ74JMYb0zqMdc2tGXCR0sLjdTT3HG7BMCim403gXnZ07pxt3BQ3F6GWwB6WYZtihb90kEm9MI6r+fc63SXvKrShFrMAuv2Iy8Ax3+FsZqTR3lVGu8JxFl3arGOA1vS75I1vgPj/rXnF0jl3be462PB2Qvb2Z60f1e6Hscte4="
  on:
    branch: feature-githubsync
    tags: false
    repo: 6uhrmittag/taskbutler
    python: 3.6
