language: python
cache: pip
sudo: false
python: 3.4

jobs:
  include:
  - python: 3.5
  - python: 3.6
  - python: nightly
  - python: 3.7-dev
  - stage: test
  - stage: deploy
    if: tag IS present
    install: skip
    script: skip
    python: 3.6
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: 6uhrmittag
      on:
        branch: master
        tags: true
        repo: 6uhrmittag/taskbutler
        python: 3.6
      password:
    secure: "lio5PZmYRKpJdpXofkfoiEB/oOlMJ3W5oZ3m8ArxKwMqjr/cFrYEtQFmuGEGea75g1Lw8Jp4BnYkjAziaCIG+hglzXFhFoVkAXg+oRhVEFj28rV6yCjacVxQUe5UVIrlNbDEgmyhm/sJwHki29X31EmE7CCbIKKaSWHhtmYq+df0Vb5PP1UGdG6U/T9O8Xxrq5WsL4NRi8pC82V2IDSYzpWwWarjy4cHXS+fndHXFC3bS73cJYGdHeTdyTck/osi0pX/7dk65AxNMOMRx1hv0kv/ISZEOJnmwhuYnq0Dt1vTEK+bVgWHFPWNH/7Y59UPSRONY4S0R61dDXslZ+kyOmCsi+nFVvviQGsxX61paOR1bcIt3zv1sZIL/LtFFOFhx7cd60wlO5k7ALMu+BMIXcttQhesTpGgT0bukZGCKmIZ/ImOie2oHHj4BTpw0LT5ynhOn0mPAeLnHqc7+5YEzJoY+bcjMV0qGOO5JrnXvX8rAAUw2hJ1JBCsPA9hyHw80a4w6Y4/wiX550xKFsrtyxddEqW2/acLguMGdk833su8qhpK5ZV9hQZ8nNM5X+4fBY0IBYfIKas+nMTeloApfCGhal/zhgrxJ9LvYB3jp/nWFB2mq6kLXYVZHphokXT94UZ3vFoW/VhJQ3EpK23uH5Ac8rbCc/F0M7xBb8aLXj0="
      #server: https://test.pypi.org/legacy/

only:
- master

install: pip install -U tox-travis
before_script:
- git clone https://github.com/sstephenson/bats.git /tmp/bats
- mkdir -p /tmp/local
- bash /tmp/bats/install.sh /tmp/local
- export PATH=$PATH:/tmp/local/bin
script: tox



