language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: 6uhrmittag
  password:
    secure: hF9hyGs7jR0K24u5rVshot9SgAIVrnulVMGsguFT0FVSCIW1Vcu6x2AaFniuVJvrTGk33vAxttRPGDulymMr8fkHipFiZ7CU/pkSNwNTNU1P+pzXdLoNQp41CmqWjXkc+9yCLjh0q4+gaXiYWfln58owmMtWtQcodcg+2tRHRi9U8xzLkJLI9vK89P1lclfqGa4q5Dnsi1DTLD4ZdROEeFZiLIRV+3K+Ytew1A2eJAMEKiwG3pBTJByg3WkV/j5pGU3yzElHj0njy6IoPyxvfIyu22UGIgsLFc9ulJ6G9SS9ykp6XwPbueDGAsLNla5xkNWDg4LHPgYBHDKsAwRyceYXLnY4oy9mIEHl9FdVMo0QXPh7LZ/mPO6y7s3ml1kERfnUoL12gC1Zs8aI1GFLK56/D/GlbJpw/ZN3N1Gekhn2mP94UlvIU2Si7mUlUs9fT/PCWtOiZQI94IIRT4WBB+SaF0CpBVlIVtA1oNoHTiFxMMf6dnOf2Q2lmJMIiZZo94r5HuXMxj7pqh9EWOAYlx+8ZwM///V9uRHm6EwK33aU6LKCOdOvpCAMnsjTUjejh4cjSkTZNXNsdwY0u3ywTJ/gGM+977Ovpm6oIW2HTHbU2msMijwuAVfxc+yXVKC0NWu4E26K4+U4m+nuB4MRYRZNH4oNBRECh1eMMDts5kU=
  on:
    branch: feature-githubsync
    tags: false
    repo: 6uhrmittag/taskbutler
    python: 3.6
