Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision :shell, path: "vagrant_bootstrap.sh"
  config.vm.synced_folder "vagrant", "/home/vagrant/taskbutlerloc"
end